---
# Database config
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/employee
     username: root
     password: 1234
     driver-class-name: com.mysql.jdbc.Driver
  jpa:
     properties:
       hibernate:
         cache:
           use_second_level_cache: false
    show-sql: true

# Web config
server:
  contextPath: /secret-santa

# Dev config
spring:
  profiles:
    active: dev

# The root of REST API in URL
api:
  rest:
    root: /rest
  version: @rest.api.version@
management:
  context-path: /manage

# Path to directory with Employees dumped files
dir:
  employees: /var/secret-santa
slack:
  enable: false
  webHook: https://hooks.slack.com/services/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

# ActiveMQ
spring:
  activemq:
    broker-url:
      tcp: //172.18.60.142:61616
spring:
  activemq:
    user: admin
  activemq:
    password: admin
queue:
  input: input
  output: output

ssanta:
  useJmsForImport: false

# Jms auto startup disable
spring:
  jms:
    listener:
      auto-startup: false

server:
  port: 5000
